# Generated by Django 5.1.4 on 2024-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_site", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="last_name",
            new_name="city",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
