# Generated by Django 5.1.4 on 2024-12-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_site", "0005_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
